# #####################################################################
# Automatically generated by qmake (2.01a) ven ago 10 16:49:21 2012
# #####################################################################
include(QtTestUtil/QtTestUtil.pri)
CONFIG += qt \
    qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . \
    ..

# Input
SOURCES += TestInputDigitale.cpp \
    QtTestUtil/SimpleChecker.cpp \
    ../InputDigitale.cpp \
    ../AbstractInputOutputDigitale.cpp \
    ../helper.cpp
HEADERS += ../InputDigitale.h \
    ../AbstractInputOutputDigitale.h \
    ../helper.h

# Add an extra 'make check' target.
QMAKE_EXTRA_TARGETS = check
check.commands = \$(MAKE) \
    && \
    ./$(QMAKE_TARGET)

# Cleanup the checker on 'make clean'
QMAKE_CLEAN += $(QMAKE_TARGET)
